import cremacionFullNIMobile from "../../../../pageMobile/cremacionMobile/cremacionFullNI/cremacionFullNIMobile";
import carroComprasMobile from "../../../../pageMobile/carroComprasMobile/carroComprasMobile/carroComprasMobile";
import webpay3Mobile from "../../../../pageMobile/carroComprasMobile/webpayMobile/webpay3Mobile";
import authenticatorWebpayMobile from "../../../../pageMobile/carroComprasMobile/webpayMobile/autentificacionMobile";
import checkoutReciboMobile from "../../../../pageMobile/carroComprasMobile/reciboMobile/checkoutReciboMobile";

describe('test cremacion-basico-NI', () => {
    beforeEach(function()  {
        cy.clearCookies();   
        cy.clearLocalStorage();
        Cypress.on('uncaught:exception', (err, runnable) => {
            // ...
            return false;
        });

        cy.fixture('Datos').then((datos) =>{
            this.datos = datos
        })
    });   
    //{nombre historia}
    it('Cremacion - Basico -NI -Descanso vidriado -Mobile', function() {
        cremacionFullNIMobile.ingresoCremacionFullNIMobile(this.datos.Url)
        cremacionFullNIMobile.agregarVelatorioPremium()
        cremacionFullNIMobile.agregarFunerariaPremiumDestacado()
        cremacionFullNIMobile.agregarDescansoVidriado()
        cremacionFullNIMobile.revisarAgregarCarrito()
        cremacionFullNIMobile.revisarPreciosVelatorio()
        cremacionFullNIMobile.revisarPreciosFuneraria()
        cremacionFullNIMobile.revisarPreciosDescanso()
        cremacionFullNIMobile.precionarCarroCompra()
        carroComprasMobile.revisarVelatorioResumen()
        carroComprasMobile.revisarFunerariaResumen()
        carroComprasMobile.revisarDescansoResumen()
        carroComprasMobile.precionarIrComprar()
        carroComprasMobile.formularioDatosPersonales(this.datos.Formulario)
        carroComprasMobile.formularioContacto(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoPrimerServico(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoSegundoServicio(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoTercerServicio(this.datos.Formulario)
        carroComprasMobile.TerminosCondicionesPagar()
        webpay3Mobile.selectTarjetas()
        webpay3Mobile.ingresoTarjetaDebito(this.datos.Formulario)
        authenticatorWebpayMobile.formularioTransbankAceptar(this.datos.Formulario)
        checkoutReciboMobile.validarPaginaAprobada()
        checkoutReciboMobile.revisarDescansoResumen()
    })
    //{nombre historia}
    it('Cremacion - Basico -NI -Descanso pared -Mobile', function() {
        cremacionFullNIMobile.ingresoCremacionFullNIMobile(this.datos.Url)
        cremacionFullNIMobile.agregarVelatorioBasico()
        cremacionFullNIMobile.agregarFunerariaTradicion()
        cremacionFullNIMobile.agregarDescansoPared()
        cremacionFullNIMobile.revisarAgregarCarrito()
        cremacionFullNIMobile.revisarPreciosVelatorio()
        cremacionFullNIMobile.revisarPreciosFuneraria()
        cremacionFullNIMobile.revisarPreciosDescanso()
        cremacionFullNIMobile.precionarCarroCompra()
        carroComprasMobile.revisarVelatorioResumen()
        carroComprasMobile.revisarFunerariaResumen()
        carroComprasMobile.revisarDescansoResumen()
        carroComprasMobile.precionarIrComprar()
        carroComprasMobile.formularioDatosPersonales(this.datos.Formulario)
        carroComprasMobile.formularioContacto(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoPrimerServico(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoSegundoServicio(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoTercerServicio(this.datos.Formulario)
        carroComprasMobile.TerminosCondicionesPagar()
        webpay3Mobile.selectTarjetas()
        webpay3Mobile.ingresoTarjetaDebito(this.datos.Formulario)
        authenticatorWebpayMobile.formularioTransbankAceptar(this.datos.Formulario)
        checkoutReciboMobile.validarPaginaAprobada()
        checkoutReciboMobile.revisarDescansoResumen()
    })
    //{nombre historia}
    it('Cremacion - Basico -NI -Descanso flores premium -Mobile', function() {
        cremacionFullNIMobile.ingresoCremacionFullNIMobile(this.datos.Url)
        cremacionFullNIMobile.agregarVelatorioEstandar()
        cremacionFullNIMobile.agregarFunerariaTradicionDestacado()
        cremacionFullNIMobile.agregarDescansoFloresPremium()
        cremacionFullNIMobile.revisarAgregarCarrito()
        cremacionFullNIMobile.revisarPreciosVelatorio()
        cremacionFullNIMobile.revisarPreciosFuneraria()
        cremacionFullNIMobile.revisarPreciosDescanso()
        cremacionFullNIMobile.precionarCarroCompra()
        carroComprasMobile.revisarVelatorioResumen()
        carroComprasMobile.revisarFunerariaResumen()
        carroComprasMobile.revisarDescansoResumen()
        carroComprasMobile.precionarIrComprar()
        carroComprasMobile.formularioDatosPersonales(this.datos.Formulario)
        carroComprasMobile.formularioContacto(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoPrimerServico(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoSegundoServicio(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoTercerServicio(this.datos.Formulario)
        carroComprasMobile.TerminosCondicionesPagar()
        webpay3Mobile.selectTarjetas()
        webpay3Mobile.ingresoTarjetaDebito(this.datos.Formulario)
        authenticatorWebpayMobile.formularioTransbankAceptar(this.datos.Formulario)
        checkoutReciboMobile.validarPaginaAprobada()
        checkoutReciboMobile.revisarDescansoResumen()
    })
    //{nombre historia}
    it('Cremacion - Basico -NI -Descanso flores -Mobile', function() {
        cremacionFullNIMobile.ingresoCremacionFullNIMobile(this.datos.Url)
        cremacionFullNIMobile.agregarVelatorioEstandar()
        cremacionFullNIMobile.agregarFunerariaSustentable()
        cremacionFullNIMobile.agregarDescansoFlores()
        cremacionFullNIMobile.revisarAgregarCarrito()
        cremacionFullNIMobile.revisarPreciosVelatorio()
        cremacionFullNIMobile.revisarPreciosFuneraria()
        cremacionFullNIMobile.revisarPreciosDescanso()
        cremacionFullNIMobile.precionarCarroCompra()
        carroComprasMobile.revisarVelatorioResumen()
        carroComprasMobile.revisarFunerariaResumen()
        carroComprasMobile.revisarDescansoResumen()
        carroComprasMobile.precionarIrComprar()
        carroComprasMobile.formularioDatosPersonales(this.datos.Formulario)
        carroComprasMobile.formularioContacto(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoPrimerServico(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoSegundoServicio(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoTercerServicio(this.datos.Formulario)
        carroComprasMobile.TerminosCondicionesPagar()
        webpay3Mobile.selectTarjetas()
        webpay3Mobile.ingresoTarjetaDebito(this.datos.Formulario)
        authenticatorWebpayMobile.formularioTransbankAceptar(this.datos.Formulario)
        checkoutReciboMobile.validarPaginaAprobada()
        checkoutReciboMobile.revisarDescansoResumen()
    })
    //{nombre historia}
    it('Cremacion - Basico -NI -Descanso memorial -Mobile', function() {
        cremacionFullNIMobile.ingresoCremacionFullNIMobile(this.datos.Url)
        cremacionFullNIMobile.agregarVelatorioPremium()
        cremacionFullNIMobile.agregarFunerariaPremium()
        cremacionFullNIMobile.agregarDescansoMemoriar()
        cremacionFullNIMobile.revisarAgregarCarrito()
        cremacionFullNIMobile.revisarPreciosVelatorio()
        cremacionFullNIMobile.revisarPreciosFuneraria()
        cremacionFullNIMobile.revisarPreciosDescanso()
        cremacionFullNIMobile.precionarCarroCompra()
        carroComprasMobile.revisarVelatorioResumen()
        carroComprasMobile.revisarFunerariaResumen()
        carroComprasMobile.revisarDescansoResumen()
        carroComprasMobile.precionarIrComprar()
        carroComprasMobile.formularioDatosPersonales(this.datos.Formulario)
        carroComprasMobile.formularioContacto(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoPrimerServico(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoSegundoServicio(this.datos.Formulario)
        carroComprasMobile.formularioFallecidoTercerServicio(this.datos.Formulario)
        carroComprasMobile.TerminosCondicionesPagar()
        webpay3Mobile.selectTarjetas()
        webpay3Mobile.ingresoTarjetaDebito(this.datos.Formulario)
        authenticatorWebpayMobile.formularioTransbankAceptar(this.datos.Formulario)
        checkoutReciboMobile.validarPaginaAprobada()
        checkoutReciboMobile.revisarDescansoResumen()
    })
})