import FunnelFunerariaNIMobile from "../../../../pageMobile/funnelMobile/funnelFunerariaNIPageMobile";
import ResumenPagoPageMobile from "../../../../pageMobile/funnelMobile/resumenPago/resumenPagoMobile";
import webpay3Mobile from "../../../../pageMobile/carroComprasMobile/webpayMobile/webpay3Mobile";
import authenticatorWebpayMobile from "../../../../pageMobile/carroComprasMobile/webpayMobile/autentificacionMobile";
import checkoutReciboMobile from "../../../../pageMobile/carroComprasMobile/reciboMobile/checkoutReciboMobile";

describe('', () => {
    beforeEach(() => {
        Cypress.on('uncaught:exception', (err, runnable) => {
            // ...
            return false;
          });
    });

    //
    it('Ingresar flujo funeraria NI Mobile', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()

    })

    //Con servicio de cremacion base - ceremonia despedida especial - anafora cofres full- descanzo de cnizas especial - memorial del recuerdo
    it('Comprar plan basico -Necesito cremacion', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanBasico()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionPlanBasico()
        FunnelFunerariaNIMobile.verMasVelatorioBasico()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioBasico()
        FunnelFunerariaNIMobile.seleccionNecesitoCremacion()
        FunnelFunerariaNIMobile.seccionServicioCremacionBase()
        FunnelFunerariaNIMobile.verMasCeremoniaDespeidaEspecial()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionCeremoniaDespeidaEspecial()
        FunnelFunerariaNIMobile.verMasAnaforaCofreFull()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionAnaforaCofreFull()
        FunnelFunerariaNIMobile.verMasEntregaCenizasEspecial()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.selecionEntregaCenizasEspecial()
        FunnelFunerariaNIMobile.verMasMemorialDelRecuerdo()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionaMemorialDelRecuerdo()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })
    //

    //Con servicio de plan tradicion - cremacion base - despedida con coro- anafora madera bascia incluida - entrega cenizas inclida - jarin de flores
    it('Comprar plan tradicion -Necesito cremacion', () => {
      
        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanTradicional()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarPlanTradicional()
        FunnelFunerariaNIMobile.verMasVelatorioCafeteriaEstandar()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioCafeteriaEstandar()
        FunnelFunerariaNIMobile.seleccionNecesitoCremacion()
        FunnelFunerariaNIMobile.seccionServicioCremacionBase()
        FunnelFunerariaNIMobile.verMasCeremoniaDespedidaConCoro()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.selecionCeremoniaDespedidaConCoro()
        FunnelFunerariaNIMobile.verMasAnaforaMaderaBasicaIncluida()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionAnaforaMaderaBasicaIncluida()
        FunnelFunerariaNIMobile.verMasEntregaCenizasIncluida()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionEntregaCenizasIncluida()
        FunnelFunerariaNIMobile.verMasJardinFlores()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.selecionarJardinFlores()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })

    //
    it('Comprar plan sustentable -Necesito cremacion', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanSustentable()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarPlanSustentable()
        FunnelFunerariaNIMobile.verMasVelatorioCafeteriaPremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioCafeteriaPremium()
        FunnelFunerariaNIMobile.seleccionNecesitoCremacion()
        FunnelFunerariaNIMobile.seccionServicioCremacionBase()
        FunnelFunerariaNIMobile.verMasCermmoniaDeDespedidaIncluida()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionCermmoniaDeDespedidaIncluida()
        FunnelFunerariaNIMobile.verMasAnaforaCofrePremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionAnaforaCofrePremium()
        FunnelFunerariaNIMobile.verMasEntregaCenizasIncluida()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionEntregaCenizasIncluida()
        FunnelFunerariaNIMobile.verMasJardinFloresPremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarJardinFloresPremium()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })

    //
    it('Comprar plan tradicion destacada -Necesito cremacion', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanTradicionalDestacado()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarPlanTradicionalDestacado()
        FunnelFunerariaNIMobile.verMasVelatorioCafeteriaPremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioCafeteriaPremium()
        FunnelFunerariaNIMobile.seleccionNecesitoCremacion()
        FunnelFunerariaNIMobile.seccionServicioCremacionBase()
        FunnelFunerariaNIMobile.verMasCeremoniaDespedidaEspecialConCoro()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionCeremoniaDespedidaEspecialConCoro()
        FunnelFunerariaNIMobile.verMasAnaforaCofrePremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionAnaforaCofrePremium()
        FunnelFunerariaNIMobile.verMasEntregaCenizasIncluida()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionEntregaCenizasIncluida()
        FunnelFunerariaNIMobile.verMasColumbarioPared()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarColumbarioPared()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })

    //
    it('Comprar plan premium -Necesito cremacion', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanSustentable()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarPlanSustentable()
        FunnelFunerariaNIMobile.verMasVelatorioCafeteriaPremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioCafeteriaPremium()
        FunnelFunerariaNIMobile.seleccionNecesitoCremacion()
        FunnelFunerariaNIMobile.seccionServicioCremacionBase()
        FunnelFunerariaNIMobile.verMasCermmoniaDeDespedidaIncluida()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionCermmoniaDeDespedidaIncluida()
        FunnelFunerariaNIMobile.verMasAnaforaCofrePremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionAnaforaCofrePremium()
        FunnelFunerariaNIMobile.verMasEntregaCenizasIncluida()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionEntregaCenizasIncluida()
        FunnelFunerariaNIMobile.verMasColumbarioVidriado()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarColumbarioVidriado()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })

    //
    it('Comprar plan tradicion Destacado -Necesito Sepultura', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanTradicionalDestacado()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarPlanTradicionalDestacado()
        FunnelFunerariaNIMobile.verMasVelatorioCafeteriaPremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioCafeteriaPremium()
        FunnelFunerariaNIMobile.seleccionNecesitoSepultura()
        FunnelFunerariaNIMobile.seccionServicioCremacionBase()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })

    //
    it('Comprar plan homenaje premium -Necesito Sepultura', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanHomenajePremium()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarPlanHomenajePremium()
        FunnelFunerariaNIMobile.verMasVelatorioBasico()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioBasico()
        FunnelFunerariaNIMobile.seleccionNecesitoSepultura()
        FunnelFunerariaNIMobile.seccionServicioCremacionBase()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })

    //
    it('Comprar plan homenaje premium destado -Necesito Sepultura', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanHomenajePremiumDestacado()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarPlanHomenajePremiumDestacado()
        FunnelFunerariaNIMobile.verMasVelatorioCafeteriaEstandar()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioCafeteriaEstandar()
        FunnelFunerariaNIMobile.seleccionNecesitoSepultura()
        FunnelFunerariaNIMobile.seccionServicioCremacionBase()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })

    //
    it('Comprar plan basico -Continuar sin estos servicios', () => {

        FunnelFunerariaNIMobile.inicioFlujoCremacion()
        FunnelFunerariaNIMobile.seleccionRegionComuna()
        FunnelFunerariaNIMobile.formularioCuentanoDeTi()
        FunnelFunerariaNIMobile.verMasPlanBasico()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionPlanBasico()
        FunnelFunerariaNIMobile.verMasVelatorioBasico()
        FunnelFunerariaNIMobile.SeleccionarVolverSidenav()
        FunnelFunerariaNIMobile.seleccionarVelatorioBasico()
        FunnelFunerariaNIMobile.seleccionContinuarSinEstosServicios()
        ResumenPagoPageMobile.completarDatos()
        ResumenPagoPageMobile.formularioComprador()
        ResumenPagoPageMobile.checkTerminosCondiciones()
        webpay3Mobile.precionarTarjetas()
        webpay3Mobile.ingresoTarjetaDebito()
        authenticatorWebpayMobile.formularioTransbankAceptar()
        checkoutReciboMobile.validarAprobacionFunnel()
    })
})